FROM openjdk:8-jdk-alpine
VOLUME /tmp
EXPOSE 8081
ARG JAR_FILE=target/ProfileMicroserviceConsumer-0.0.1-SNAPSHOT.jar
ADD ${JAR_FILE} profile-consumer.jar
ENTRYPOINT ["java","-Djava.security.egd=file:/dev/./urandom","-jar","/profile-consumer.jar"]